TPA and TPHere (#4).
iceBear67/WithMyFriends pull request #19
Opened 2021-10-23 04:13 UTC by qyl27

Signed-off-by: 秋雨落 <i@rain.cx>

2021-10-23 04:19 UTC, iceBear67 requested changes
Please

2021-10-23 04:19 UTC, iceBear67 commented on basic/src/main/java/withmyfriends/basic/modules/teleport/TeleportRequest.java
> +        Bukkit.getScheduler().scheduleSyncRepeatingTask(WithMyFriends.getInstance(), () -> {
这里是为了清理 Map 吗？

2021-10-23 04:19 UTC, iceBear67 commented on basic/src/main/java/withmyfriends/basic/modules/teleport/TeleportRequest.java
> +    public class Request {
这里可以改成 `public static class Request`，non-static 的 class 会和外部实例关联上，此处没有这种需求因此会徒增占用

2021-10-23 04:19 UTC, iceBear67 commented on basic/src/main/java/withmyfriends/basic/modules/teleport/TeleportRequest.java
> +    public class Request {
如果 Request 有可能作为暴露出去的 API 的话，考虑一下 `@Data`  

这块可以用 lombok 的写法，不过你似乎没怎么用过 lombok

2021-10-23 04:19 UTC, iceBear67 commented on basic/src/main/java/withmyfriends/basic/modules/teleport/TeleportRequest.java
> +        public final long createTime;
private fields + `@RequiredArgsConstructor`，`createTime` 可以直接去掉 final 然后用 `System.currentTimeMillis();`  

当然，你可以考虑用 `Instant` 得到更好的可读性。

2021-10-23 04:20 UTC, qyl27 commented on basic/src/main/java/withmyfriends/basic/modules/teleport/TeleportRequest.java
> +        Bukkit.getScheduler().scheduleSyncRepeatingTask(WithMyFriends.getInstance(), () -> {
是的

2021-10-23 04:20 UTC, qyl27 commented on basic/src/main/java/withmyfriends/basic/modules/teleport/TeleportRequest.java
> +    public class Request {
好的， Request 不会被暴露出去，所以也许不需要 @Data ？

2021-10-23 04:21 UTC, qyl27 commented on basic/src/main/java/withmyfriends/basic/modules/teleport/TeleportRequest.java
> +        public final long createTime;
@RequiredArgsConstructor是……？

2021-10-23 04:22 UTC, iceBear67 commented on basic/src/main/java/withmyfriends/basic/modules/teleport/TeleportRequest.java
> +        Bukkit.getScheduler().scheduleSyncRepeatingTask(WithMyFriends.getInstance(), () -> {
可以考虑使用 Guava 线程安全的 [Cache](https://www.cnblogs.com/rickiyang/p/11074159.html)

2021-10-23 04:23 UTC, iceBear67 commented on basic/src/main/java/withmyfriends/basic/modules/teleport/TeleportRequest.java
> +        public final long createTime;
Lombok 对于被这个注解标注的类会生成对于所有 final field 的构造器

2021-10-23 04:23 UTC, iceBear67 commented on basic/src/main/java/withmyfriends/basic/modules/teleport/TeleportRequest.java
> +    public class Request {
那就不用了

2021-10-24 00:53 UTC, iceBear67 commented on basic/src/main/java/withmyfriends/basic/modules/teleport/TeleportRequest.java
> +        private String failed = "&cYou just denied the request. Nothing will be take place.";
这块 I18N ...

2021-10-24 00:53 UTC, iceBear67 commented on basic/src/main/java/withmyfriends/basic/modules/teleport/TeleportRequest.java
> +        private String failed = "&cYou just denied the request. Nothing will be take place.";
我后续加个I18N API再弄好了，先留着

2021-10-28 00:41 UTC, iceBear67 requested changes
Almost done!

2021-10-28 00:41 UTC, iceBear67 commented on basic/src/main/java/withmyfriends/basic/modules/teleport/TeleportRequest.java
> -                    player.sendMessage(ColoredString.of(getConfig().accepted));
这个直接放到上面其实也可以

2021-10-28 00:41 UTC, iceBear67 commented on basic/src/main/java/withmyfriends/basic/modules/teleport/TeleportRequest.java
> +            if (request.target == player.getUniqueId()) {
这里是不是应该用`UUID#equals()`呢?如果玩家离线->上线的话这里就有可能有问题，因为`==`对比的是两个对象的内存地址。

2021-10-28 01:07 UTC, merged

2021-10-28 09:08 UTC, iceBear67 commented
Thanks for your contribution.